CREATE TABLE IF NOT EXISTS energy_offers (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    provider_id INT UNSIGNED NULL,
    provider_name VARCHAR(160) NOT NULL,
    offer_code VARCHAR(80) NOT NULL,
    offer_name VARCHAR(200) NOT NULL,
    supply_type ENUM('luce','gas') NOT NULL,
    customer_type VARCHAR(40) NULL,
    offer_type VARCHAR(40) NULL,
    price_type VARCHAR(20) NULL,
    p_fix_f DECIMAL(12,6) NULL,
    p_fix_v DECIMAL(12,6) NULL,
    p_vol_f1 DECIMAL(12,6) NULL,
    p_vol_f2 DECIMAL(12,6) NULL,
    p_vol_f3 DECIMAL(12,6) NULL,
    p_vol_bf1 DECIMAL(12,6) NULL,
    p_vol_bf23 DECIMAL(12,6) NULL,
    p_vol_mono DECIMAL(12,6) NULL,
    p_vol DECIMAL(12,6) NULL,
    alpha DECIMAL(12,6) NULL,
    region VARCHAR(120) NULL,
    province VARCHAR(120) NULL,
    municipality VARCHAR(160) NULL,
    offer_url VARCHAR(255) NULL,
    valid_from DATE NULL,
    valid_to DATE NULL,
    source VARCHAR(40) NOT NULL DEFAULT 'arera',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY idx_energy_offers_code (offer_code, supply_type),
    KEY idx_energy_offers_provider (provider_id),
    KEY idx_energy_offers_supply (supply_type),
    KEY idx_energy_offers_valid (valid_from, valid_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
